name: Deploy Crypto Web

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare release directory
    runs-on: [self-hosted]
    outputs:
      release: ${{ steps.set-release.outputs.release }}
    steps:
      - name: Generate and output release dir
        id: set-release
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          echo "release=$TIMESTAMP" >> $GITHUB_OUTPUT
          mkdir -p "${{ secrets.DEPLOY_PATH }}/releases/$TIMESTAMP"

      - name: Clone repo
        run: |
          git clone --depth=1 --branch main https://github.com/${{ github.repository }} "${{ secrets.DEPLOY_PATH }}/releases/${{ steps.set-release.outputs.release }}"

      - name: Remove storage directory
        run: |
          rm -rf "${{ secrets.DEPLOY_PATH }}/releases/${{ steps.set-release.outputs.release }}/storage"

      - name: Link shared files
        run: |
          ln -snf "${{ secrets.DEPLOY_PATH }}/shared/.env" "${{ secrets.DEPLOY_PATH }}/releases/${{ steps.set-release.outputs.release }}/.env"
          ln -snf "${{ secrets.DEPLOY_PATH }}/shared/storage" "${{ secrets.DEPLOY_PATH }}/releases/${{ steps.set-release.outputs.release }}/storage"

  composer:
    name: Install Composer dependencies
    needs: prepare
    runs-on: [self-hosted]
    steps:
      - name: Composer install
        run: |
          # Print the full release path for debugging
          RELEASE_PATH="${{ secrets.DEPLOY_PATH }}/releases/${{ needs.prepare.outputs.release }}"
          echo "Full release path: $RELEASE_PATH"
          
          # Check if the directory exists
          if [ ! -d "$RELEASE_PATH" ]; then
            echo "ERROR: Release directory does not exist: $RELEASE_PATH"
            exit 1
          fi
          
          # Change to release directory
          cd "$RELEASE_PATH"
          echo "Current directory: $(pwd)"
          ls -la
          
          # Run composer
          composer install --no-dev --optimize-autoloader

  npm:
    name: Build frontend assets
    needs: composer
    runs-on: [self-hosted]
    steps:
      - name: Debug release path
        run: |
          echo "Release path: ${{ secrets.DEPLOY_PATH }}/releases/${{ needs.prepare.outputs.release }}"
          ls -la "${{ secrets.DEPLOY_PATH }}/releases/${{ needs.prepare.outputs.release }}"

      - name: NPM build
        run: |
          # Print the full release path for debugging
          RELEASE_PATH="${{ secrets.DEPLOY_PATH }}/releases/${{ needs.prepare.outputs.release }}"
          echo "Full release path: $RELEASE_PATH"
          
          # Check if the directory exists
          if [ ! -d "$RELEASE_PATH" ]; then
            echo "ERROR: Release directory does not exist: $RELEASE_PATH"
            exit 1
          fi
          
          # Check if package.json exists
          if [ ! -f "$RELEASE_PATH/package.json" ]; then
            echo "ERROR: package.json not found in $RELEASE_PATH"
            ls -la "$RELEASE_PATH"
            exit 1
          fi
          
          # Change to release directory and run npm commands with explicit path
          cd "$RELEASE_PATH"
          echo "Current directory: $(pwd)"
          ls -la
          
          # Run npm commands with explicit path to package.json
          /usr/bin/npm --prefix "$RELEASE_PATH" install
          /usr/bin/npm --prefix "$RELEASE_PATH" run build-only
          rm -rf "$RELEASE_PATH/node_modules"

  migrate:
    name: Run migrations and seed
    needs: npm
    runs-on: [self-hosted]
    steps:
      - name: Artisan migrate
        run: |
          # Print the full release path for debugging
          RELEASE_PATH="${{ secrets.DEPLOY_PATH }}/releases/${{ needs.prepare.outputs.release }}"
          echo "Full release path: $RELEASE_PATH"
          
          # Check if the directory exists
          if [ ! -d "$RELEASE_PATH" ]; then
            echo "ERROR: Release directory does not exist: $RELEASE_PATH"
            exit 1
          fi
          
          # Change to release directory
          cd "$RELEASE_PATH"
          echo "Current directory: $(pwd)"
          
          # Run migrations
          php artisan migrate --seed --force

  activate:
    name: Activate release & restart FPM
    needs: migrate
    runs-on: [self-hosted]
    steps:
      - name: Switch symlink and restart PHP
        run: |
          ln -sfn "${{ secrets.DEPLOY_PATH }}/releases/${{ needs.prepare.outputs.release }}" "${{ secrets.DEPLOY_PATH }}/current"
          /usr/bin/systemctl restart php8.3-fpm

  cleanup:
    name: Cleanup old releases
    needs: activate
    runs-on: [self-hosted]
    steps:
      - name: Purge old releases (keep 3)
        run: |
          cd "${{ secrets.DEPLOY_PATH }}/releases"
          ls -1t | tail -n +4 | xargs -r rm -rf